 
# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests

    schedule:
      interval: "weekly"

    target-branch: "development"

    assignees:
      - "wsEM2022-24"

    reviewers:
      - "TaoN23"
      - "13Anonym"

    milestone: 8

    labels:
      - "reviewing"
      - "DevOps"
      - "npm update"
      - "dependencies"
      - "dependabot"
    