name: "CI Pipeline"

on:
  pull_request:
    branches:
      - development
      - main


jobs:
  linting:
    runs-on: ubuntu-latest

    steps:
      - name: "checkout"
        uses: actions/checkout@v3
      
      - name: "setup node"
        uses: actions/setup-node@v3
        with:
          node-version: 16.13.x
          cache: npm

      - name: "packages install"
        run: npm ci
      
      - name: "run eslint & prettier"
        run:  npx eslint src/** --fix
