name: Issue managing v1

on:
  issues:
    types:
      - opened

jobs:
  label_issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:
      - uses: actions/checkout@v2
      - name: check priority label
        id: haslabel
        uses: DanielTamkin/HasLabel@v1.0.4
        with:
          contains: 'priority::'


      - name: add priority label
        uses: andymckay/labeler@e6c4322d0397f3240f0e7e30a33b5c5df2d39e90
        if: steps.haslabel.outputs.unlabeled
        with:
          add-labels: "priority::low"
          repo-token: ${{ secrets.GITHUB_TOKEN }}


      - name: check state label
        id: hasstatelabel
        uses: DanielTamkin/HasLabel@v1.0.4
        with:
          exact: 'pending'
      

      - name: add state label
        uses: andymckay/labeler@e6c4322d0397f3240f0e7e30a33b5c5df2d39e90
        if: steps.hasstatelabel.outputs.unlabeled
        with:
          add-labels: "pending"
          repo-token: ${{ secrets.GITHUB_TOKEN }}


        

